# register new user
POST http://localhost:4000/register
Content-Type: application/json

{
    "name":"Marka",
    "email":"marksa@gmail.com",
    "password":"Biggie@2025"
}


###
# login existing user
POST http://localhost:4000/login
Content-Type: application/json

{
    "name":"Marka",
    "password":"Biggie@2025"
}


###
# get all users
GET http://localhost:4000/get-users


###
# get user by id
GET http://localhost:4000/get/2


###
# update user by id
PUT http://localhost:4000/update/5
Content-Type: application/json

{
    "name":"Big Man",
    "email":"biggie@gmail.com",
    "password":"Biggie@2025"
}

###
# delete user by id
DELETE http://localhost:4000/delete/7

